# -*- coding: utf-8 -*-
"""Day71.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qsz9DcDAZhhtbgmdPmMPSvhfUhUFllOU
"""

import pandas as pd

df = pd.read_csv('salaries_by_college_major.csv')
clean_df = df.dropna()

#groupby columns
print(clean_df.groupby('Group').count())

#find mean salary by groupby
print(clean_df.groupby('Group').mean())

#number formats in the output
pd.options.display.float_format = '{:,.2f}'.format
print(clean_df.groupby('Group').mean())

